Core:
  PPU Decoder: Recompiler (LLVM)
  PPU Threads: 8
  PPU Debug: false
  PPU Calling History: false
  Save LLVM logs: false
  Use LLVM CPU: ""
  Max LLVM Compile Threads: 0
  PPU LLVM Greedy Mode: false
  LLVM Precompilation: true
  Thread Scheduler Mode: Operating System
  Set DAZ and FTZ: false
  SPU Decoder: Recompiler (LLVM)
  SPU Reservation Busy Waiting Percentage 1: 100
  SPU Reservation Busy Waiting Enabled: false
  SPU GETLLAR Busy Waiting Percentage: 100
  Disable SPU GETLLAR Spin Optimization: false
  SPU Debug: false
  MFC Debug: false
  Preferred SPU Threads: 6
  SPU delay penalty: 3
  SPU loop detection: false
  Max SPURS Threads: 6
  SPU Block Size: Safe
  Accurate SPU DMA: false
  Accurate SPU Reservations: true
  Accurate Cache Line Stores: false
  Accurate RSX reservation access: false
  RSX FIFO Fetch Accuracy: Atomic
  SPU Verification: true
  SPU Cache: true
  SPU Profiler: false
  PPU Profiler: false
  MFC Commands Shuffling Limit: 0
  MFC Commands Timeout: 0
  MFC Commands Shuffling In Steps: false
  XFloat Accuracy: Approximate
  Accurate PPU 128-byte Reservation Op Max Length: 0
  Stub PPU Traps: 0
  Precise SPU Verification: false
  PPU LLVM Java Mode Handling: true
  Use Accurate DFMA: false
  PPU Set Saturation Bit: false
  PPU Accurate Non-Java Mode: false
  PPU Fixup Vector NaN Values: false
  PPU Accurate Vector NaN Values: false
  PPU Set FPCC Bits: false
  Debug Console Mode: false
  Hook static functions: false
  Libraries Control:
    []
  HLE lwmutex: false
  SPU LLVM Lower Bound: 0
  SPU LLVM Upper Bound: 18446744073709551615
  Clocks scale: 100
  SPU Wake-Up Delay: 0
  SPU Wake-Up Delay Thread Mask: 63
  Max CPU Preempt Count: 50
  Allow RSX CPU Preemptions: true
  Sleep Timers Accuracy: Usleep Only
  Usleep Time Addend: 0
  Performance Report Threshold: 500
  Enable Performance Report: false
  Assume External Debugger: false
  SPU Reservation Busy Waiting Percentage: 0
  RSX FIFO Accuracy: Atomic
  Enable TSX: Disabled
  TSX Transaction First Limit: 800
  TSX Transaction Second Limit: 2000
VFS:
  Enable /host_root/: false
  Initialize Directories: true
  Limit disk cache size: false
  Disk cache maximum size (MB): 5120
  Empty /dev_hdd0/tmp/: true
Video:
  Renderer: Vulkan
  Resolution: 1280x720
  Aspect ratio: 16:9
  Frame limit: Infinite
  Second Frame Limit: 0
  MSAA: Auto
  Shader Mode: Async Shader Recompiler
  Shader Precision: Low
  Write Color Buffers: true
  Write Depth Buffer: false
  Read Color Buffers: false
  Read Depth Buffer: false
  Handle RSX Memory Tiling: false
  Log shader programs: false
  VSync: true
  Debug output: false
  Debug overlay: false
  Renderdoc Compatibility Mode: false
  Use GPU texture scaling: false
  Stretch To Display Area: false
  Force High Precision Z buffer: false
  Strict Rendering Mode: false
  Disable ZCull Occlusion Queries: false
  Disable Video Output: false
  Disable Vertex Cache: false
  Disable FIFO Reordering: false
  Enable Frame Skip: false
  Force CPU Blit: false
  Disable On-Disk Shader Cache: false
  Disable Vulkan Memory Allocator: false
  Use full RGB output range: true
  Strict Texture Flushing: false
  Multithreaded RSX: false
  Relaxed ZCULL Sync: false
  Force Hardware MSAA Resolve: false
  3D Display Enabled: false
  3D Display Mode: Disabled
  Debug Program Analyser: false
  Accurate ZCULL stats: true
  Consecutive Frames To Draw: 1
  Consecutive Frames To Skip: 1
  Resolution Scale: 200
  Anisotropic Filter Override: 16
  Texture LOD Bias Addend: 0
  Minimum Scalable Dimension: 16
  Shader Compiler Threads: 0
  Driver Recovery Timeout: 1000000
  Driver Wake-Up Delay: 20
  Vblank Rate: 141
  Vblank NTSC Fixup: false
  DECR memory layout: false
  Allow Host GPU Labels: false
  Disable MSL Fast Math: false
  Disable Asynchronous Memory Manager: false
  Output Scaling Mode: FidelityFX Super Resolution
  Record With Overlays: true
  Vulkan:
    Adapter: NVIDIA GeForce RTX 4060
    Force FIFO present mode: false
    Force primitive restart flag: false
    Exclusive Fullscreen Mode: Disable
    Asynchronous Texture Streaming 2: false
    FidelityFX CAS Sharpening Intensity: 70
    Asynchronous Queue Scheduler: Safe
    VRAM allocation limit (MB): 65536
    Use Re-BAR for GPU uploads: true
  Performance Overlay:
    Enabled: false
    Enable Framerate Graph: false
    Enable Frametime Graph: false
    Framerate datapoints: 50
    Frametime datapoints: 170
    Detail level: Medium
    Framerate graph detail level: All
    Frametime graph detail level: All
    Metrics update interval (ms): 350
    Font size (px): 10
    Position: Top Left
    Font: n023055ms.ttf
    Horizontal Margin (px): 50
    Vertical Margin (px): 50
    Center Horizontally: false
    Center Vertically: false
    Opacity (%): 70
    Body Color (hex): "#FFE138FF"
    Body Background (hex): "#002339FF"
    Title Color (hex): "#F26C24FF"
    Title Background (hex): "#00000000"
  Shader Loading Dialog:
    Allow custom background: true
    Darkening effect strength: 30
    Blur effect strength: 0
Audio:
  Renderer: XAudio2
  Audio Provider: CellAudio
  RSXAudio Avport: HDMI 0
  Dump to file: false
  Convert to 16 bit: false
  Audio Format: Stereo
  Audio Formats: 0
  Audio Channel Layout: Automatic
  Audio Device: "@@@default@@@"
  Master Volume: 100
  Enable Buffering: true
  Desired Audio Buffer Duration: 100
  Enable Time Stretching: false
  Disable Sampling Skip: false
  Time Stretching Threshold: 75
  Microphone Type: "Null"
  Microphone Devices: "@@@@@@@@@@@@"
  Music Handler: Qt
Input/Output:
  Keyboard: "Null"
  Mouse: Basic
  Camera: "Null"
  Camera type: Unknown
  Camera flip: None
  Camera ID: Default
  SDL Camera ID: Default
  Move: "Null"
  Buzz emulated controller: "Null"
  Turntable emulated controller: "Null"
  GHLtar emulated controller: "Null"
  Pad handler mode: Single-threaded
  Keep pads connected: false
  Pad handler sleep (microseconds): 1000
  Background input enabled: true
  Show move cursor: false
  Paint move spheres: false
  Allow move hue set by game: false
  Lock overlay input to player one: false
  Emulated Midi devices: Keyboardßßß@@@Keyboardßßß@@@Keyboardßßß@@@
  Load SDL GameController Mappings: true
  IO Debug overlay: false
  Mouse Debug overlay: false
  Fake Move Rotation Cone: 10
  Fake Move Rotation Cone (Vertical): 10
System:
  License Area: SCEA
  Language: English (US)
  Keyboard Type: English keyboard (US standard)
  Enter button assignment: Enter with cross
  Date Format: ddmmyyyy
  Time Format: clock24
  Console time offset (s): 0
  System Name: RPCS3-232
  Console PSID: 0x114D894871E97C1860116D0FE61F5D43
  HDD Model Name: ""
  HDD Serial Number: ""
  Process ARGV: {}
  PSID high: 0
  PSID low: 0
Net:
  Internet enabled: Connected
  IP address: 0.0.0.0
  Bind address: 0.0.0.0
  DNS address: 8.8.8.8
  IP swap list: "gosredirector.ea.com==213.143.181.115&&downloads.skate.online.ea.com==213.143.181.115"
  UPNP Enabled: true
  PSN status: RPCN
  PSN Country: us
  Clans Enabled: false
Savestate:
  Start Paused: false
  Suspend Emulation Savestate Mode: false
  Compatible Savestate Mode: false
  Inspection Mode Savestates: false
  Save Disc Game Data: false
  Maximum SaveState Files: 4
  Maximum SaveState Files Space (MiB): 4096
Miscellaneous:
  Automatically start games after boot: true
  Exit RPCS3 when process finishes: false
  Pause emulation on RPCS3 focus loss: false
  Start games in fullscreen mode: false
  Prevent display sleep while running games: true
  Show trophy popups: false
  Show RPCN popups: false
  Show shader compilation hint: false
  Show PPU compilation hint: false
  Show autosave/autoload hint: false
  Show pressure intensity toggle hint: false
  Show analog limiter toggle hint: false
  Show mouse and keyboard toggle hint: false
  Show capture hints: true
  Use native user interface: true
  GDB Server: 127.0.0.1:2345
  Silence All Logs: false
  Window Title Format: "FPS: %F | %R | %V | %T [%t]"
  Pause Emulation During Home Menu: true
  Enable GameMode: false
Log: {}